#!/bin/sh
### BEGIN INIT INFO
# Provides:          furyd
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop furyd.
# Description:       This script starts/stops furyd.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

OPTS="-d"

if [ $( id -u ) != 0 ]; then
	echo "ERROR: Must be run as root"
	exit 1
fi

case "$1" in
  start)
	/usr/local/sbin/furyd $OPTS >/home/pi/log/pi.log &
	;;
  restart|reload|force-reload)
	killall furyd
	/usr/local/sbin/furyd $OPTS >/home/pi/log/pi.log &
	;;
  stop)
	killall furyd
	;;
  status)
	;;
esac

exit 0

